package com.alibaba.feathub.flink.udf.aggregation;

import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.table.types.DataType;

/**
 * An {@link AggFunc} used in sliding window transform's aggregation process.
 *
 * <p>Unless specially optimized, aggregation functions would receive pre-aggregation results
 * generated by {@link SlidingWindowPreAggFuncWrapper}, merge them and generate the final
 * aggregation result.
 */
public class SlidingWindowAggFuncWrapper<IN_T, OUT_T, ACC_T>
        implements AggFunc<ACC_T, OUT_T, ACC_T> {
    private final AggFunc<IN_T, OUT_T, ACC_T> aggFunc;

    public SlidingWindowAggFuncWrapper(AggFunc<IN_T, OUT_T, ACC_T> aggFunc) {
        this.aggFunc = aggFunc;
    }

    @Override
    public ACC_T add(ACC_T accumulator, ACC_T value, long timestamp) {
        return aggFunc.merge(accumulator, value);
    }

    @Override
    public ACC_T merge(ACC_T target, ACC_T source) {
        return aggFunc.merge(target, source);
    }

    @Override
    public ACC_T retract(ACC_T accumulator, ACC_T value) {
        return aggFunc.retractAccumulator(accumulator, value);
    }

    @Override
    public ACC_T retractAccumulator(ACC_T target, ACC_T source) {
        return aggFunc.retractAccumulator(target, source);
    }

    @Override
    public OUT_T getResult(ACC_T accumulator) {
        return aggFunc.getResult(accumulator);
    }

    @Override
    public DataType getResultDatatype() {
        return aggFunc.getResultDatatype();
    }

    @Override
    public ACC_T createAccumulator() {
        return aggFunc.createAccumulator();
    }

    @Override
    public TypeInformation<ACC_T> getAccumulatorTypeInformation() {
        return aggFunc.getAccumulatorTypeInformation();
    }
}
